name: Unit Test Coverage

on:
  pull_request:

jobs:
  unit-test-cov:
    name: Run Unit Test Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Test Coverage
        run: npm run test:unit:cov
